### ISSUE TITLE
Program freezes when completing Beneath Cursed Tides

### ISSUE THREAD

**Issue by loganpihl** [RenegadeLucien/project-tenacity#42] opened 2019-08-07 21:14 UTC
Title. When I complete Beneath Cursed Tides as an achievement, it simply doesn't do anything, and I'm forced to quit it and open it again - which doesn't fix the issue.

**Comment by RenegadeLucien** [comment] 2019-08-08 01:34
Haven't found a cause for this yet, but this looks likes the same thing as #39.

**Comment by RenegadeLucien** [comment] 2019-08-09 07:21
Found a root cause. This is due to rounding errors: when calculating for time spent on an action, the numbers were not rounded up to the next 6000th of an hour (game tick), but when actually "performing" the actions on the data, they are. This results in a small difference between the expected change on the data and the actual change on the data, which through other processing steps are magnified enough that they cause the bank value of the data to go negative, and this breaks the process and freezes the application.

Fixed this, a fix for this will be in v1.0.3 tomorrow.

**Closed by RenegadeLucien** 2019-08-09 07:21 UTC
Labels: T80
